angular.module('app-back', ['cbd.back.controllers',
                            'cbd.back.directives',
                            'cbd.back.partners.directives',
                            'cbd.back.partners.controllers',
                            'cbd.back.contacts.directives',
                            'cbd.back.contacts.controllers',
                            'cbd.back.assos.directives',
                            'cbd.back.assos.controllers',
                            'ui.tinymce',
                            'ui.bootstrap' ]);